pub use crate::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AchService {
    #[serde(rename = "achAbsorb")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ach_absorb: Option<AchAbsorbSection>,
    #[serde(rename = "achAbsorb_highPayRange")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ach_absorb_high_pay_range: Option<TemplateElement>,
    #[serde(rename = "achAbsorb_lowPayRange")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ach_absorb_low_pay_range: Option<TemplateElement>,
    #[serde(rename = "achAcceptance")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ach_acceptance: Option<AchAcceptanceElement>,
    #[serde(rename = "achFees")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ach_fees: Option<AchFeeSection>,
    #[serde(rename = "achPass_highPayRange")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ach_pass_high_pay_range: Option<TemplateElement>,
    #[serde(rename = "achPass_lowPayRange")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ach_pass_low_pay_range: Option<TemplateElement>,
    #[serde(rename = "achPassThrough")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ach_pass_through: Option<AchPassThroughSection>,
    /// Controls how to present the `batchCutoffTime` field on the application. If this field isn't sent, batch cut off time defaults to 5 ET.
    #[serde(rename = "batchCutoffTime")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub batch_cutoff_time: Option<TemplateElement>,
    #[serde(rename = "discountFrequency")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub discount_frequency: Option<TemplateElement>,
    #[serde(rename = "fundingRollup")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub funding_rollup: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gateway: Option<TemplateElement>,
    #[serde(rename = "pdfTemplateId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pdf_template_id: Option<TemplateElement>,
    #[serde(rename = "pricingPlan")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pricing_plan: Option<i64>,
    #[serde(rename = "pricingType")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pricing_type: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub processor: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider: Option<TemplateElement>,
    #[serde(rename = "tierName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tier_name: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub visible: Option<Visible>,
}
