pub use crate::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ApplicationData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub services: Option<Services>,
    #[serde(rename = "annualRevenue")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub annual_revenue: Option<Annualrevenue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Attachments>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub avgmonthly: Option<Avgmonthly>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub baddress: Option<Baddress1>,
    #[serde(rename = "baddress1")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub baddress_1: Option<Baddress2>,
    #[serde(rename = "bankData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bank_data: Option<Bank>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bcity: Option<Bcity>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bcountry: Option<Bcountry>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub binperson: Option<Binperson>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub binphone: Option<Binphone>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub binweb: Option<Binweb>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bstate: Option<Bstate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bsummary: Option<Bsummary>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub btype: Option<OwnType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bzip: Option<Bzip>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contacts: Option<ContactsField>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dbaname: Option<Dbaname>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ein: Option<Ein>,
    #[serde(rename = "externalPaypointId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_paypoint_id: Option<ExternalPaypointId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub faxnumber: Option<BoardingBusinessFax>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub highticketamt: Option<Highticketamt>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub legalname: Option<Legalname>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub license: Option<License>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub licstate: Option<Licensestate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maddress: Option<Maddress>,
    #[serde(rename = "maddress1")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maddress_1: Option<Maddress1>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mcc: Option<Mcc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mcity: Option<Mcity>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mcountry: Option<Mcountry>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mstate: Option<Mstate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mzip: Option<Mzip>,
    #[serde(rename = "orgId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub org_id: Option<Orgid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ownership: Option<Ownership>,
    #[serde(rename = "payoutAverageMonthlyVolume")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payout_average_monthly_volume: Option<PayoutAverageMonthlyVolume>,
    #[serde(rename = "payoutAverageTicketLimit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payout_average_ticket_limit: Option<PayoutAverageTicketLimit>,
    #[serde(rename = "payoutCreditLimit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payout_credit_limit: Option<PayoutCreditLimit>,
    #[serde(rename = "payoutHighTicketAmount")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payout_high_ticket_amount: Option<PayoutHighTicketAmount>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phonenumber: Option<BoardingBusinessPhone>,
    /// Email address for the applicant. This is used to send the applicant a boarding link.
    #[serde(rename = "recipientEmail")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recipient_email: Option<Email>,
    #[serde(rename = "recipientEmailNotification")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recipient_email_notification: Option<RecipientEmailNotification>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resumable: Option<Resumable>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signer: Option<SignerDataRequest>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub startdate: Option<Busstartdate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub taxfillname: Option<Taxfillname>,
    #[serde(rename = "templateId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub template_id: Option<TemplateId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ticketamt: Option<Ticketamt>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub website: Option<Website>,
    #[serde(rename = "whenCharged")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub when_charged: Option<Whencharged>,
    #[serde(rename = "whenDelivered")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub when_delivered: Option<Whendelivered>,
    #[serde(rename = "whenProvided")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub when_provided: Option<Whenprovided>,
    #[serde(rename = "whenRefunded")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub when_refunded: Option<Whenrefunded>,
    #[serde(rename = "RepCode")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rep_code: Option<RepCode>,
    #[serde(rename = "RepName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rep_name: Option<RepName>,
    #[serde(rename = "RepOffice")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rep_office: Option<RepOffice>,
    #[serde(rename = "onCreate")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub on_create: Option<OnCreate>,
}
