pub use crate::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ApplicationQueryRecord {
    #[serde(rename = "annualRevenue")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub annual_revenue: Option<Annualrevenue>,
    #[serde(rename = "averageMonthlyVolume")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub average_monthly_volume: Option<Avgmonthly>,
    #[serde(rename = "averageTicketAmount")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub average_ticket_amount: Option<Ticketamt>,
    #[serde(rename = "bAddress1")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_address_1: Option<Baddress1>,
    #[serde(rename = "bAddress2")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_address_2: Option<Baddress2>,
    #[serde(rename = "bankData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bank_data: Option<BankData>,
    #[serde(rename = "bCity")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_city: Option<Bcity>,
    #[serde(rename = "bCountry")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_country: Option<Bcountry>,
    /// The business's fax number.
    #[serde(rename = "bFax")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_fax: Option<Bphone>,
    #[serde(rename = "binPerson")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bin_person: Option<Binperson>,
    #[serde(rename = "binPhone")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bin_phone: Option<Binphone>,
    #[serde(rename = "binWeb")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bin_web: Option<Binweb>,
    #[serde(rename = "boardingLinkId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boarding_link_id: Option<BoardingLinkId>,
    #[serde(rename = "boardingStatus")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boarding_status: Option<BoardingStatus>,
    #[serde(rename = "boardingSubStatus")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boarding_sub_status: Option<BoardingStatus>,
    #[serde(rename = "bPhone")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_phone: Option<Bphone>,
    #[serde(rename = "bStartdate")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_startdate: Option<Busstartdate>,
    #[serde(rename = "bState")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_state: Option<Bstate>,
    #[serde(rename = "bSummary")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_summary: Option<Bsummary>,
    #[serde(rename = "builderData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub builder_data: Option<BuilderData>,
    #[serde(rename = "bZip")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_zip: Option<Bzip>,
    #[serde(rename = "contactData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contact_data: Option<ContactsField>,
    #[serde(rename = "createdAt")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<CreatedAt>,
    #[serde(rename = "dbaName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dba_name: Option<Dbaname>,
    #[serde(rename = "documentsRef")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub documents_ref: Option<BoardingApplicationAttachments>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ein: Option<Ein>,
    #[serde(rename = "externalPaypointId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_paypoint_id: Option<ExternalPaypointId>,
    /// Events associated with the application.
    #[serde(rename = "generalEvents")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub general_events: Option<Vec<GeneralEvents>>,
    #[serde(rename = "highTicketAmount")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub high_ticket_amount: Option<Highticketamt>,
    #[serde(rename = "idApplication")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id_application: Option<AppId>,
    #[serde(rename = "lastModified")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_modified: Option<LastModified>,
    #[serde(rename = "legalName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub legal_name: Option<Legalname>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub license: Option<License>,
    #[serde(rename = "licenseState")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub license_state: Option<Licensestate>,
    /// Object containing logo file.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logo: Option<FileContent>,
    #[serde(rename = "mAddress1")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub m_address_1: Option<Maddress>,
    #[serde(rename = "mAddress2")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub m_address_2: Option<Maddress1>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mccid: Option<String>,
    #[serde(rename = "mCity")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub m_city: Option<Mstate>,
    #[serde(rename = "mCountry")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub m_country: Option<Mcountry>,
    #[serde(rename = "mState")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub m_state: Option<Mstate>,
    #[serde(rename = "mZip")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub m_zip: Option<Mzip>,
    #[serde(rename = "orgId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub org_id: Option<Orgid>,
    #[serde(rename = "orgParentName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub org_parent_name: Option<OrgParentName>,
    #[serde(rename = "ownerData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub owner_data: Option<Ownership>,
    #[serde(rename = "ownType")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub own_type: Option<OwnType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pageidentifier: Option<PageIdentifier>,
    #[serde(rename = "recipientEmailNotification")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recipient_email_notification: Option<RecipientEmailNotification>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resumable: Option<Resumable>,
    #[serde(rename = "salesCode")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sales_code: Option<SalesCode>,
    #[serde(rename = "serviceData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_data: Option<Services>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signer: Option<SignerData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub taxfillname: Option<Taxfillname>,
    #[serde(rename = "templateId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub template_id: Option<TemplateId>,
    #[serde(rename = "websiteAddress")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub website_address: Option<Website>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub whencharged: Option<Whencharged>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub whendelivered: Option<Whendelivered>,
    #[serde(rename = "whenProvided")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub when_provided: Option<Whenprovided>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub whenrefund: Option<Whenrefunded>,
    #[serde(rename = "additionalData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_data: Option<AdditionalDataString>,
    #[serde(rename = "RepCode")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rep_code: Option<RepCode>,
    #[serde(rename = "RepName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rep_name: Option<RepName>,
    #[serde(rename = "RepOffice")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rep_office: Option<RepOffice>,
}
