pub use crate::prelude::*;

/// Details about a business.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct BusinessSection {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub baddress: Option<TemplateElement>,
    #[serde(rename = "baddress1")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub baddress_1: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bcity: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bcountry: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bstate: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub btype: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bzip: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dbaname: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ein: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub faxnumber: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub legalname: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub license: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub licstate: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maddress: Option<TemplateElement>,
    #[serde(rename = "maddress1")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maddress_1: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mcity: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mcountry: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mstate: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mzip: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phonenumber: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub startdate: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub taxfillname: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub visible: Option<Visible>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub website: Option<TemplateElement>,
    #[serde(rename = "additionalData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_data: Option<TemplateAdditionalDataSection>,
}
