pub use crate::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CardService {
    /// Controls how to present the `batchCutoffTime` field on the application. If this field isn't sent, batch cut off time defaults to 5 ET.
    #[serde(rename = "batchCutoffTime")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub batch_cutoff_time: Option<TemplateElement>,
    #[serde(rename = "cardAcceptance")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_acceptance: Option<CardAcceptanceElement>,
    #[serde(rename = "cardFees")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_fees: Option<CardFeeSection>,
    #[serde(rename = "cardFlat")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_flat: Option<CardFlatSection>,
    #[serde(rename = "cardFlat_amountxAuth")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_flat_amountx_auth: Option<TemplateElement>,
    #[serde(rename = "cardFlat_highPayRange")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_flat_high_pay_range: Option<TemplateElement>,
    #[serde(rename = "cardFlat_lowPayRange")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_flat_low_pay_range: Option<TemplateElement>,
    #[serde(rename = "cardFlat_percentxAuth")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_flat_percentx_auth: Option<TemplateElement>,
    #[serde(rename = "cardICP")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_icp: Option<CardIcpSection>,
    #[serde(rename = "cardICP_amountxAuth")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_icp_amountx_auth: Option<TemplateElement>,
    #[serde(rename = "cardICP_highPayRange")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_icp_high_pay_range: Option<TemplateElement>,
    #[serde(rename = "cardICP_lowPayRange")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_icp_low_pay_range: Option<TemplateElement>,
    #[serde(rename = "cardICP_percentxAuth")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_icp_percentx_auth: Option<TemplateElement>,
    #[serde(rename = "cardPassThrough")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_pass_through: Option<CardPassThroughSection>,
    #[serde(rename = "cardPassThrough_amountRecurring")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_pass_through_amount_recurring: Option<TemplateElement>,
    #[serde(rename = "cardPassThrough_amountxAuth")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_pass_through_amountx_auth: Option<TemplateElement>,
    #[serde(rename = "cardPassThrough_highPayRange")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_pass_through_high_pay_range: Option<TemplateElement>,
    #[serde(rename = "cardPassThrough_lowPayRange")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_pass_through_low_pay_range: Option<TemplateElement>,
    #[serde(rename = "cardPassThrough_percentRecurring")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_pass_through_percent_recurring: Option<TemplateElement>,
    #[serde(rename = "cardPassThrough_percentxAuth")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_pass_through_percentx_auth: Option<TemplateElement>,
    #[serde(rename = "discountFrequency")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub discount_frequency: Option<TemplateElement>,
    #[serde(rename = "fundingRollup")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub funding_rollup: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gateway: Option<TemplateElement>,
    #[serde(rename = "passThroughCost")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pass_through_cost: Option<TemplateElement>,
    #[serde(rename = "pdfTemplateId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pdf_template_id: Option<TemplateElement>,
    #[serde(rename = "pricingPlan")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pricing_plan: Option<i64>,
    #[serde(rename = "pricingType")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pricing_type: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub processor: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider: Option<TemplateElement>,
    #[serde(rename = "tierName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tier_name: Option<TemplateElement>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub visible: Option<Visible>,
}
