pub use crate::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct GetInvoiceRecord {
    #[serde(rename = "invoiceId")]
    pub invoice_id: InvoiceId,
    #[serde(rename = "customerId")]
    pub customer_id: CustomerId,
    #[serde(rename = "paypointId")]
    pub paypoint_id: PaypointId,
    #[serde(rename = "invoiceNumber")]
    pub invoice_number: InvoiceNumber,
    #[serde(rename = "invoiceDate")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invoice_date: Option<NaiveDate>,
    #[serde(rename = "invoiceDueDate")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invoice_due_date: Option<NaiveDate>,
    #[serde(rename = "invoiceSentDate")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::flexible_datetime::utc::option")]
    pub invoice_sent_date: Option<DateTime<Utc>>,
    #[serde(rename = "invoiceEndDate")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invoice_end_date: Option<NaiveDate>,
    #[serde(rename = "lastPaymentDate")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::flexible_datetime::utc::option")]
    pub last_payment_date: Option<DateTime<Utc>>,
    #[serde(rename = "createdAt")]
    pub created_at: CreatedAt,
    #[serde(rename = "invoiceStatus")]
    pub invoice_status: Invoicestatus,
    #[serde(rename = "invoiceType")]
    pub invoice_type: InvoiceType,
    pub frequency: Frequency,
    #[serde(rename = "paymentTerms")]
    pub payment_terms: Terms,
    #[serde(rename = "termsConditions")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub terms_conditions: Option<TermsConditions>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tax: Option<Tax>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub discount: Option<Discount>,
    #[serde(rename = "invoiceAmount")]
    pub invoice_amount: InvoiceAmount,
    #[serde(rename = "invoicePaidAmount")]
    pub invoice_paid_amount: InvoicePaidAmount,
    #[serde(rename = "freightAmount")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub freight_amount: Option<FreightAmount>,
    #[serde(rename = "dutyAmount")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duty_amount: Option<DutyAmount>,
    #[serde(rename = "purchaseOrder")]
    pub purchase_order: PurchaseOrder,
    /// First name of the recipient of the invoice.
    #[serde(rename = "firstName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// Last name of the recipient of the invoice.
    #[serde(rename = "lastName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// Company name of the recipient of the invoice.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub company: Option<String>,
    #[serde(rename = "shippingAddress1")]
    pub shipping_address_1: Shippingaddress,
    #[serde(rename = "shippingAddress2")]
    pub shipping_address_2: Shippingaddressadditional,
    #[serde(rename = "shippingCity")]
    pub shipping_city: Shippingcity,
    #[serde(rename = "shippingState")]
    pub shipping_state: Shippingstate,
    #[serde(rename = "shippingZip")]
    pub shipping_zip: Shippingzip,
    #[serde(rename = "shippingFromZip")]
    pub shipping_from_zip: ShippingFromZip,
    #[serde(rename = "shippingCountry")]
    pub shipping_country: Shippingcountry,
    #[serde(rename = "shippingEmail")]
    pub shipping_email: Email,
    #[serde(rename = "shippingPhone")]
    pub shipping_phone: String,
    #[serde(rename = "summaryCommodityCode")]
    pub summary_commodity_code: SummaryCommodityCode,
    pub items: Vec<BillItem>,
    #[serde(rename = "Customer")]
    pub customer: PayorDataResponse,
    #[serde(rename = "paylinkId")]
    pub paylink_id: PaylinkId,
    #[serde(rename = "billEvents")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bill_events: Option<BillEvents>,
    #[serde(rename = "scheduledOptions")]
    pub scheduled_options: BillOptions,
    #[serde(rename = "PaypointLegalname")]
    pub paypoint_legalname: String,
    #[serde(rename = "PaypointDbaname")]
    pub paypoint_dbaname: Dbaname,
    #[serde(rename = "PaypointEntryname")]
    pub paypoint_entryname: Entrypointfield,
    #[serde(rename = "ParentOrgName")]
    pub parent_org_name: OrgParentName,
    #[serde(rename = "AdditionalData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_data: Option<AdditionalDataMap>,
    #[serde(rename = "DocumentsRef")]
    pub documents_ref: DocumentsRef,
    #[serde(rename = "externalPaypointID")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_paypoint_id: Option<ExternalPaypointId>,
}