pub use crate::prelude::*;

/// Complete transaction details including payment information, customer data, and processing metadata. This is returned when includeDetails=true.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TransactionDetailRecord {
    #[serde(rename = "parentOrgName")]
    pub parent_org_name: OrgParentName,
    #[serde(rename = "paypointDbaname")]
    pub paypoint_dbaname: Dbaname,
    #[serde(rename = "paypointLegalname")]
    pub paypoint_legalname: Legalname,
    #[serde(rename = "paypointEntryname")]
    pub paypoint_entryname: Entrypointfield,
    #[serde(rename = "paymentTransId")]
    pub payment_trans_id: String,
    #[serde(rename = "connectorName")]
    pub connector_name: String,
    #[serde(rename = "externalProcessorInformation")]
    pub external_processor_information: ExternalProcessorInformation,
    #[serde(rename = "gatewayTransId")]
    pub gateway_trans_id: String,
    #[serde(rename = "orderId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_id: Option<OrderId>,
    pub method: TransactionDetailRecordMethod,
    #[serde(rename = "batchNumber")]
    pub batch_number: BatchNumber,
    #[serde(rename = "batchAmount")]
    pub batch_amount: f64,
    #[serde(rename = "payorId")]
    pub payor_id: PayorId,
    #[serde(rename = "paymentData")]
    pub payment_data: TransactionDetailPaymentData,
    #[serde(rename = "transStatus")]
    pub trans_status: TransStatus,
    #[serde(rename = "paypointId")]
    pub paypoint_id: PaypointId,
    #[serde(rename = "totalAmount")]
    pub total_amount: f64,
    #[serde(rename = "netAmount")]
    pub net_amount: f64,
    #[serde(rename = "feeAmount")]
    pub fee_amount: FeeAmount,
    #[serde(rename = "settlementStatus")]
    pub settlement_status: SettlementStatus,
    pub operation: Operation,
    #[serde(rename = "responseData")]
    pub response_data: TransactionDetailResponseData,
    pub source: Source,
    #[serde(rename = "scheduleReference")]
    pub schedule_reference: i64,
    #[serde(rename = "orgId")]
    pub org_id: Orgid,
    #[serde(rename = "refundId")]
    pub refund_id: RefundId,
    #[serde(rename = "returnedId")]
    pub returned_id: ReturnedId,
    #[serde(rename = "chargebackId")]
    pub chargeback_id: ChargebackId,
    #[serde(rename = "retrievalId")]
    pub retrieval_id: RetrievalId,
    #[serde(rename = "transAdditionalData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trans_additional_data: Option<serde_json::Value>,
    #[serde(rename = "invoiceData")]
    pub invoice_data: TransactionDetailInvoiceData,
    #[serde(rename = "entrypageId")]
    pub entrypage_id: EntrypageId,
    #[serde(rename = "externalPaypointID")]
    pub external_paypoint_id: ExternalPaypointId,
    #[serde(rename = "isValidatedACH")]
    pub is_validated_ach: bool,
    #[serde(rename = "transactionTime")]
    pub transaction_time: String,
    pub customer: TransactionDetailCustomer,
    #[serde(rename = "splitFundingInstructions")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub split_funding_instructions: Option<SplitFunding>,
    #[serde(rename = "cfeeTransactions")]
    pub cfee_transactions: Vec<QueryCFeeTransaction>,
    #[serde(rename = "transactionEvents")]
    pub transaction_events: Vec<TransactionDetailEvent>,
    #[serde(rename = "pendingFeeAmount")]
    pub pending_fee_amount: PendingFeeAmount,
    #[serde(rename = "riskFlagged")]
    pub risk_flagged: RiskFlagged,
    #[serde(rename = "riskFlaggedOn")]
    pub risk_flagged_on: RiskFlaggedOn,
    #[serde(rename = "riskStatus")]
    pub risk_status: RiskStatus,
    #[serde(rename = "riskReason")]
    pub risk_reason: RiskReason,
    #[serde(rename = "riskAction")]
    pub risk_action: RiskAction,
    #[serde(rename = "riskActionCode")]
    pub risk_action_code: RiskActionCode,
    #[serde(rename = "deviceId")]
    pub device_id: Device,
    #[serde(rename = "achSecCode")]
    pub ach_sec_code: AchSecCode,
    #[serde(rename = "achHolderType")]
    pub ach_holder_type: AchHolderType,
    #[serde(rename = "ipAddress")]
    pub ip_address: IpAddress,
    #[serde(rename = "isSameDayACH")]
    pub is_same_day_ach: bool,
    #[serde(rename = "walletType")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wallet_type: Option<String>,
}
