pub use crate::prelude::*;

/// Indicate the format of report file to be generated by the engine.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum NotificationReportRequestContentFileFormat {
    #[serde(rename = "json")]
    Json,
    #[serde(rename = "csv")]
    Csv,
    #[serde(rename = "xlsx")]
    Xlsx,
}
impl fmt::Display for NotificationReportRequestContentFileFormat {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Self::Json => "json",
            Self::Csv => "csv",
            Self::Xlsx => "xlsx",
        };
        write!(f, "{}", s)
    }
}
