pub use crate::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub struct NotificationReportRequestContent {
    /// The notification's event name.
    #[serde(rename = "eventType")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_type: Option<String>,
    /// Indicate the format of report file to be generated by the engine.
    #[serde(rename = "fileFormat")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_format: Option<NotificationReportRequestContentFileFormat>,
    /// Array of pairs key:value to insert in request body to target in **method** = *report-web*.
    #[serde(rename = "internalData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub internal_data: Option<Vec<KeyValueDuo>>,
    /// The kind report to generate.
    #[serde(rename = "reportName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub report_name: Option<NotificationReportRequestContentReportName>,
    #[serde(rename = "timeZone")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<Timezone>,
    /// Used internally to reference the entity or object generating the event.
    #[serde(rename = "transactionId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
    /// Array of pairs key:value to insert in header of request to target in **method** = *report-web*.
    #[serde(rename = "webHeaderParameters")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub web_header_parameters: Option<Vec<KeyValueDuo>>,
}
