pub use crate::prelude::*;

/// The notification's event name.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum NotificationContentEventType {
    ApprovedPayment,
    AuthorizedPayment,
    DeclinedPayment,
    OriginatedPayment,
    SettledPayment,
    SubscriptionCreated,
    SubscriptionUpdated,
    SubscriptionCanceled,
    SubscriptionCompleted,
    FundedPayment,
    VoidedPayment,
    RefundedPayment,
    HoldTransaction,
    ReleasedTransaction,
    HoldBatch,
    ReleasedBatch,
    TransferDisabledCreditFund,
    TransferDisabledDebitFund,
    TransferNotAvailableBalance,
    TransferReturn,
    TransferSuccess,
    TransferSuspended,
    TransferError,
    SendReceipt,
    RecoveredTransaction,
    CreatedApplication,
    ApprovedApplication,
    FailedBoardingApplication,
    SubmittedApplication,
    UnderWritingApplication,
    ActivatedMerchant,
    ReceivedChargeBack,
    ChargebackUpdated,
    ReceivedRetrieval,
    RetrievalUpdated,
    ReceivedAchReturn,
    HoldingApplication,
    DeclinedApplication,
    BoardingApplication,
    FraudAlert,
    InvoiceSent,
    InvoicePaid,
    InvoiceCreated,
    BillPaid,
    BillApproved,
    BillDisApproved,
    BillCanceled,
    BillProcessing,
    CardCreated,
    CardActivated,
    CardDeactivated,
    CardExpired,
    CardExpiring,
    CardLimitUpdated,
    BatchClosed,
    BatchNotClosed,
    PayOutFunded,
    PayOutProcessed,
    PayOutCanceled,
    PayOutPaid,
    PayOutReturned,
    PayoutSubscriptionCreated,
    PayoutSubscriptionUpdated,
    PayoutSubscriptionCanceled,
    PayoutSubscriptionCompleted,
    PayoutSubscriptionReminder,
    #[serde(rename = "importFileReceived")]
    ImportFileReceived,
    #[serde(rename = "importFileProcessed")]
    ImportFileProcessed,
    #[serde(rename = "importFileError")]
    ImportFileError,
    #[serde(rename = "exportFileSent")]
    ExportFileSent,
    #[serde(rename = "exportFileError")]
    ExportFileError,
    FailedEmailNotification,
    FailedWebNotification,
    #[serde(rename = "FailedSMSNotification")]
    FailedSmsNotification,
    UserPasswordExpiring,
    UserPasswordExpired,
    TransactionNotFound,
    SystemAlert,
    Report,
}
impl fmt::Display for NotificationContentEventType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Self::ApprovedPayment => "ApprovedPayment",
            Self::AuthorizedPayment => "AuthorizedPayment",
            Self::DeclinedPayment => "DeclinedPayment",
            Self::OriginatedPayment => "OriginatedPayment",
            Self::SettledPayment => "SettledPayment",
            Self::SubscriptionCreated => "SubscriptionCreated",
            Self::SubscriptionUpdated => "SubscriptionUpdated",
            Self::SubscriptionCanceled => "SubscriptionCanceled",
            Self::SubscriptionCompleted => "SubscriptionCompleted",
            Self::FundedPayment => "FundedPayment",
            Self::VoidedPayment => "VoidedPayment",
            Self::RefundedPayment => "RefundedPayment",
            Self::HoldTransaction => "HoldTransaction",
            Self::ReleasedTransaction => "ReleasedTransaction",
            Self::HoldBatch => "HoldBatch",
            Self::ReleasedBatch => "ReleasedBatch",
            Self::TransferDisabledCreditFund => "TransferDisabledCreditFund",
            Self::TransferDisabledDebitFund => "TransferDisabledDebitFund",
            Self::TransferNotAvailableBalance => "TransferNotAvailableBalance",
            Self::TransferReturn => "TransferReturn",
            Self::TransferSuccess => "TransferSuccess",
            Self::TransferSuspended => "TransferSuspended",
            Self::TransferError => "TransferError",
            Self::SendReceipt => "SendReceipt",
            Self::RecoveredTransaction => "RecoveredTransaction",
            Self::CreatedApplication => "CreatedApplication",
            Self::ApprovedApplication => "ApprovedApplication",
            Self::FailedBoardingApplication => "FailedBoardingApplication",
            Self::SubmittedApplication => "SubmittedApplication",
            Self::UnderWritingApplication => "UnderWritingApplication",
            Self::ActivatedMerchant => "ActivatedMerchant",
            Self::ReceivedChargeBack => "ReceivedChargeBack",
            Self::ChargebackUpdated => "ChargebackUpdated",
            Self::ReceivedRetrieval => "ReceivedRetrieval",
            Self::RetrievalUpdated => "RetrievalUpdated",
            Self::ReceivedAchReturn => "ReceivedAchReturn",
            Self::HoldingApplication => "HoldingApplication",
            Self::DeclinedApplication => "DeclinedApplication",
            Self::BoardingApplication => "BoardingApplication",
            Self::FraudAlert => "FraudAlert",
            Self::InvoiceSent => "InvoiceSent",
            Self::InvoicePaid => "InvoicePaid",
            Self::InvoiceCreated => "InvoiceCreated",
            Self::BillPaid => "BillPaid",
            Self::BillApproved => "BillApproved",
            Self::BillDisApproved => "BillDisApproved",
            Self::BillCanceled => "BillCanceled",
            Self::BillProcessing => "BillProcessing",
            Self::CardCreated => "CardCreated",
            Self::CardActivated => "CardActivated",
            Self::CardDeactivated => "CardDeactivated",
            Self::CardExpired => "CardExpired",
            Self::CardExpiring => "CardExpiring",
            Self::CardLimitUpdated => "CardLimitUpdated",
            Self::BatchClosed => "BatchClosed",
            Self::BatchNotClosed => "BatchNotClosed",
            Self::PayOutFunded => "PayOutFunded",
            Self::PayOutProcessed => "PayOutProcessed",
            Self::PayOutCanceled => "PayOutCanceled",
            Self::PayOutPaid => "PayOutPaid",
            Self::PayOutReturned => "PayOutReturned",
            Self::PayoutSubscriptionCreated => "PayoutSubscriptionCreated",
            Self::PayoutSubscriptionUpdated => "PayoutSubscriptionUpdated",
            Self::PayoutSubscriptionCanceled => "PayoutSubscriptionCanceled",
            Self::PayoutSubscriptionCompleted => "PayoutSubscriptionCompleted",
            Self::PayoutSubscriptionReminder => "PayoutSubscriptionReminder",
            Self::ImportFileReceived => "importFileReceived",
            Self::ImportFileProcessed => "importFileProcessed",
            Self::ImportFileError => "importFileError",
            Self::ExportFileSent => "exportFileSent",
            Self::ExportFileError => "exportFileError",
            Self::FailedEmailNotification => "FailedEmailNotification",
            Self::FailedWebNotification => "FailedWebNotification",
            Self::FailedSmsNotification => "FailedSMSNotification",
            Self::UserPasswordExpiring => "UserPasswordExpiring",
            Self::UserPasswordExpired => "UserPasswordExpired",
            Self::TransactionNotFound => "TransactionNotFound",
            Self::SystemAlert => "SystemAlert",
            Self::Report => "Report",
        };
        write!(f, "{}", s)
    }
}
