pub use crate::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PaypointData {
    #[serde(rename = "address1")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_1: Option<AddressNullable>,
    #[serde(rename = "address2")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_2: Option<AddressAddtlNullable>,
    #[serde(rename = "bankData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bank_data: Option<BankData>,
    #[serde(rename = "boardingId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boarding_id: Option<BoardingId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<CityNullable>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contacts: Option<ContactsField>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<CountryNullable>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub credentials: Option<Vec<PayabliCredentialsPascal>>,
    #[serde(rename = "dbaName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dba_name: Option<Dbaname>,
    #[serde(rename = "externalPaypointID")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_paypoint_id: Option<ExternalPaypointId>,
    /// Fax number
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fax: Option<PhoneNumber>,
    #[serde(rename = "idPaypoint")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id_paypoint: Option<Idpaypoint>,
    #[serde(rename = "legalName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub legal_name: Option<Legalname>,
    #[serde(rename = "parentOrg")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_org: Option<OrgData>,
    #[serde(rename = "paypointStatus")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paypoint_status: Option<Paypointstatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone: Option<PhoneNumber>,
    #[serde(rename = "serviceData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_data: Option<Services>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<StateNullable>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<PaypointSummary>,
    #[serde(rename = "timeZone")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<Timezone>,
    #[serde(rename = "websiteAddress")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub website_address: Option<Website>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub zip: Option<Zip>,
}
