pub use crate::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct BatchDetailResponseRecord {
    #[serde(rename = "Id")]
    pub id: i64,
    #[serde(rename = "Method")]
    pub method: String,
    #[serde(rename = "WalletType")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wallet_type: Option<String>,
    #[serde(rename = "SettledAmount")]
    pub settled_amount: f64,
    #[serde(rename = "Type")]
    pub r#type: String,
    #[serde(rename = "BatchNumber")]
    pub batch_number: BatchNumber,
    #[serde(rename = "BatchAmount")]
    pub batch_amount: f64,
    #[serde(rename = "PaymentTransId")]
    pub payment_trans_id: String,
    #[serde(rename = "PaymentTransStatus")]
    pub payment_trans_status: i64,
    #[serde(rename = "ScheduleReference")]
    pub schedule_reference: i64,
    #[serde(rename = "GatewayTransId")]
    pub gateway_trans_id: String,
    #[serde(rename = "OrderId")]
    pub order_id: OrderId,
    #[serde(rename = "TransMethod")]
    pub trans_method: String,
    #[serde(rename = "PaymentData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_data: Option<QueryPaymentData>,
    #[serde(rename = "NetAmount")]
    pub net_amount: Netamountnullable,
    #[serde(rename = "Operation")]
    pub operation: Operation,
    #[serde(rename = "Category")]
    pub category: Category,
    #[serde(rename = "Source")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<Source>,
    #[serde(rename = "Status")]
    pub status: i64,
    #[serde(rename = "TransactionTime")]
    pub transaction_time: TransactionTime,
    #[serde(rename = "Customer")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer: Option<QueryTransactionPayorData>,
    #[serde(rename = "SettlementDate")]
    #[serde(with = "crate::core::flexible_datetime::offset")]
    pub settlement_date: DateTime<FixedOffset>,
    #[serde(rename = "PaymentSettlementStatus")]
    pub payment_settlement_status: i64,
    #[serde(rename = "BatchStatus")]
    pub batch_status: i64,
    #[serde(rename = "DepositDate")]
    pub deposit_date: DepositDate,
    #[serde(rename = "ExpectedDepositDate")]
    pub expected_deposit_date: ExpectedDepositDate,
    #[serde(rename = "MaskedAccount")]
    pub masked_account: Maskedaccount,
    #[serde(rename = "CreatedAt")]
    pub created_at: CreatedAt,
    #[serde(rename = "PaypointLegalname")]
    pub paypoint_legalname: Legalname,
    #[serde(rename = "ResponseData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response_data: Option<QueryResponseData>,
    #[serde(rename = "PaypointDbaname")]
    pub paypoint_dbaname: Dbaname,
    #[serde(rename = "ParentOrgName")]
    pub parent_org_name: OrgParentName,
    #[serde(rename = "ParentOrgId")]
    pub parent_org_id: i64,
    #[serde(rename = "PaypointEntryname")]
    pub paypoint_entryname: Entrypointfield,
    #[serde(rename = "DeviceId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_id: Option<Device>,
    #[serde(rename = "RetrievalId")]
    pub retrieval_id: RetrievalId,
    #[serde(rename = "ChargebackId")]
    pub chargeback_id: ChargebackId,
    #[serde(rename = "AchHolderType")]
    pub ach_holder_type: AchHolderType,
    #[serde(rename = "AchSecCode")]
    pub ach_sec_code: AchSecCode,
    #[serde(rename = "ConnectorName")]
    pub connector_name: String,
    #[serde(rename = "EntrypageId")]
    pub entrypage_id: EntrypageId,
    #[serde(rename = "FeeAmount")]
    pub fee_amount: FeeAmount,
    #[serde(rename = "OrgId")]
    pub org_id: Orgid,
    #[serde(rename = "PayorId")]
    pub payor_id: PayorId,
    #[serde(rename = "PaypointId")]
    pub paypoint_id: PaypointId,
    #[serde(rename = "PendingFeeAmount")]
    pub pending_fee_amount: PendingFeeAmount,
    #[serde(rename = "RefundId")]
    pub refund_id: RefundId,
    #[serde(rename = "ReturnedId")]
    pub returned_id: ReturnedId,
    #[serde(rename = "splitFundingInstructions")]
    pub split_funding_instructions: SplitFunding,
    #[serde(rename = "TotalAmount")]
    pub total_amount: f64,
    #[serde(rename = "CfeeTransactions")]
    pub cfee_transactions: Vec<QueryCFeeTransaction>,
    #[serde(rename = "invoiceData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invoice_data: Option<BillData>,
    #[serde(rename = "TransactionEvents")]
    pub transaction_events: Vec<QueryTransactionEvents>,
    #[serde(rename = "externalPaypointID")]
    pub external_paypoint_id: ExternalPaypointId,
    #[serde(rename = "isHold")]
    pub is_hold: i64,
}
