pub use crate::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct QueryEntrypointResponseRecordsItem {
    #[serde(rename = "AverageMonthlyVolume")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub average_monthly_volume: Option<Avgmonthly>,
    #[serde(rename = "AverageTicketAmount")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub average_ticket_amount: Option<Avgticketamt>,
    #[serde(rename = "BAddress1")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_address_1: Option<Baddress1>,
    #[serde(rename = "BAddress2")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_address_2: Option<Baddress2>,
    #[serde(rename = "BankData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bank_data: Option<BankData>,
    #[serde(rename = "BCity")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_city: Option<Bcity>,
    #[serde(rename = "BCountry")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_country: Option<Bcountry>,
    /// The business's fax number.
    #[serde(rename = "BFax")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_fax: Option<Bphone>,
    #[serde(rename = "BinPerson")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bin_person: Option<Binperson>,
    #[serde(rename = "BinPhone")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bin_phone: Option<Binphone>,
    #[serde(rename = "BinWeb")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bin_web: Option<Binweb>,
    #[serde(rename = "BoardingId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boarding_id: Option<BoardingId>,
    #[serde(rename = "BPhone")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_phone: Option<Bphone>,
    #[serde(rename = "BStartdate")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_startdate: Option<Busstartdate>,
    #[serde(rename = "BState")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_state: Option<Bstate>,
    #[serde(rename = "BSummary")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_summary: Option<Bsummary>,
    #[serde(rename = "BTimeZone")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_time_zone: Option<Timezone>,
    #[serde(rename = "BZip")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub b_zip: Option<Bzip>,
    #[serde(rename = "ContactData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contact_data: Option<ContactsField>,
    #[serde(rename = "CreatedAt")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<CreatedAt>,
    #[serde(rename = "DbaName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dba_name: Option<Dbaname>,
    #[serde(rename = "DocumentsRef")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub documents_ref: Option<String>,
    #[serde(rename = "Ein")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ein: Option<Ein>,
    #[serde(rename = "EntryPoints")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entry_points: Option<Vec<PaypointEntryConfig>>,
    #[serde(rename = "externalPaypointID")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_paypoint_id: Option<ExternalPaypointId>,
    #[serde(rename = "ExternalProcessorInformation")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_processor_information: Option<ExternalProcessorInformation>,
    #[serde(rename = "HighTicketAmount")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub high_ticket_amount: Option<Highticketamt>,
    #[serde(rename = "IdPaypoint")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id_paypoint: Option<Idpaypoint>,
    #[serde(rename = "LastModified")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_modified: Option<LastModified>,
    #[serde(rename = "LegalName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub legal_name: Option<Legalname>,
    #[serde(rename = "License")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub license: Option<License>,
    #[serde(rename = "LicenseState")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub license_state: Option<Licensestate>,
    #[serde(rename = "MAddress1")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub m_address_1: Option<Maddress>,
    #[serde(rename = "MAddress2")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub m_address_2: Option<Maddress1>,
    #[serde(rename = "Mccid")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mccid: Option<String>,
    #[serde(rename = "MCity")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub m_city: Option<Mcity>,
    #[serde(rename = "MCountry")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub m_country: Option<Mcountry>,
    #[serde(rename = "MState")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub m_state: Option<Mstate>,
    #[serde(rename = "MZip")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub m_zip: Option<Mzip>,
    #[serde(rename = "OrgId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub org_id: Option<Orgid>,
    #[serde(rename = "OrgParentName")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub org_parent_name: Option<OrgParentName>,
    #[serde(rename = "OwnerData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub owner_data: Option<Ownership>,
    #[serde(rename = "OwnType")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub own_type: Option<OwnType>,
    #[serde(rename = "PaypointStatus")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paypoint_status: Option<Paypointstatus>,
    #[serde(rename = "SalesCode")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sales_code: Option<SalesCode>,
    #[serde(rename = "ServiceData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_data: Option<Services>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<PaypointSummary>,
    #[serde(rename = "Taxfillname")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub taxfillname: Option<Taxfillname>,
    #[serde(rename = "TemplateId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub template_id: Option<TemplateId>,
    /// Business website.
    #[serde(rename = "WebsiteAddress")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub website_address: Option<Website>,
    #[serde(rename = "Whencharged")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub whencharged: Option<Whencharged>,
    #[serde(rename = "Whendelivered")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub whendelivered: Option<Whendelivered>,
    #[serde(rename = "Whenprovided")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub whenprovided: Option<Whenprovided>,
    #[serde(rename = "Whenrefund")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub whenrefund: Option<Whenrefunded>,
}
