pub use crate::prelude::*;

/// Information about the application's signer.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub struct SignerData {
    /// The signer's ID. This is automatically generated by Payabli.
    #[serde(rename = "signerUuid")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signer_uuid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<SignerName>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ssn: Option<SignerSsn>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dob: Option<SignerDob>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone: Option<SignerPhone>,
    /// The signer's email address.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<Email>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<Signeraddress>,
    #[serde(rename = "address1")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_1: Option<SignerAddress1>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<SignerCity>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<SignerState>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub zip: Option<SignerZip>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<SignerCountry>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub acceptance: Option<SignerAcceptance>,
    /// Reference to the signed document.
    #[serde(rename = "signedDocumentReference")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signed_document_reference: Option<String>,
    #[serde(rename = "pciAttestation")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pci_attestation: Option<PciAttestation>,
    #[serde(rename = "attestationDate")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attestation_date: Option<AttestationDate>,
    #[serde(rename = "signDate")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sign_date: Option<SignDate>,
    #[serde(rename = "additionalData")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_data: Option<AdditionalDataString>,
}
